# -*- coding: utf-8 -*-
{
    'name': "nciavarella Documents",
    'summary': "nciavarella customizations for documents",
    'license': 'OPL-1',
    'author': "Niccolò Ciavarella",
    'category': '',
    'version': '14.0.1',
    'website': "http://www.nciavarella.me",
    'depends': ['mail'],
    'data': ['security/ir.model.access.csv',
             'views/nciavarella_documents_actions.xml',
             'views/nciavarella_documents_form.xml',
             'views/nciavarella_documents_menus.xml',
             'views/nciavarella_documents_search.xml',
             'views/nciavarella_documents_tree.xml',
             'reports/nciavarella_documents_reports_actions.xml',
             'reports/nciavarella_documents_report.xml'],
    'application': True,
    'installable': True,
}