# -*- coding: utf-8 -*-
{
    'name': "nciavarella Custom",
    'summary': "nciavarella customizations",
    'license': 'OPL-1',
    'author': "Niccolò Ciavarella",
    'category': '',
    'version': '15.0.2',
    'website': "http://www.nciavarella.me",
    'depends': ['account'],
    'data': ['security/ir.model.access.csv',
             'security/groups.xml',
             'data/account_menuitem_delete.xml',
             'views/account_tax_form.xml',
             'views/account_menuitem.xml',
             'views/account_move_form.xml',
             'views/account_move_tree.xml',
             'views/account_invoice_tree.xml',
             'views/product_product_form.xml',
             'views/activity_costs_form.xml',
             'views/activity_costs_tree.xml',
             'views/res_partner_form.xml',
             'views/res_partner_tree.xml',
             'report/report_invoice_document.xml'],
    'application': False,
    'installable': True,
}